apiVersion: 1

datasources:
  - name: Timestream
    type: grafana-timestream-datasource
    access: proxy
    isDefault: true
    jsonData:
      authType: default
      defaultRegion: us-east-1
      defaultDatabase: manufacturing-analytics-db-dev
      defaultTable: sensor_metrics
    version: 1
    editable: true
